### ISSUE TITLE
[CONVERTER] Использование конвертера

### ISSUE THREAD

**Issue by anry-das** [VladTertishniy/LabWork2SpringAppLastFm#1]
Для использования зарегистрированного конвертера достаточно заинжектить
`private final ConversionService conversionService;`
и использовать его.
Использовать `Converter<String, Album> stringToAlbumConverter` не нужно, т.к. Спринг на этом этапе сам знает, какой конвертер вызвать, исходя из типов <S, T>

**Comment by VladTertishniy** [comment]
commit d27d956
